name: React Build

on:
  push:
    branches: ['main']

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: TaniuOp/akomegaag
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          publish_dir: ./build
